language: generic

os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - GMODPROJ_BUILD_MODE=development

install:
  - sh ./bin/bootstrap.sh

after_install:
  - ./bin/luvi --version
  - ./bin/luvit --version
  - ./bin/gmodproj --version

build:
  - ./bin/gmodproj bin build development
    
    