version: "{build}"

platform: x64

branches:
  only:
    - master

environment:
  GMODPROJ_BUILD_MODE: development

install:
  - bin\bootstrap.bat

before_build:
  - bin\luvi --version & exit 0
  - bin\luvit --version & exit 0
  - bin\gmodproj version

build_script:
  - bin\gmodproj bin build development

after_test:
  - bin\gmodproj bin build production

artifacts:
  - path: dist\*

deploy:
  - provider: GitHub
    artifact: dist\*
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true  
