version: "{build}"

platform: x64

branches:
  only:
    - master
    - latest

environment:
  GMODPROJ_BUILD_MODE: development

install:
  - bin\bootstrap.bat

before_build:
  - bin\luvi --version 2>&1
  - bin\luvit --version 2>&1
  - bin\gmodproj version

build_script:
  - bin\gmodproj bin build development

on_success:
  - bin\gmodproj bin build production

artifacts:
  - path: dist\*
